<a href="https://colab.research.google.com/github/sejallotliker/Advanced_python/blob/main/PyTorch_concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch essential Training

This repository contains the fundamentals of PyTorch library and how to create Tensors which can be used in deep learning.

In [ ]:
import torch

print(torch.__version__)
print(torch.cuda.is_available()) #GPU available

2.9.0+cu126
True


#Creating a tensor : CPU example

In [ ]:
#addition
first_tens = torch.tensor([[12, 10, 11, 9], [13, 15, 14, 16]])
second_tens = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])

add_tens = first_tens + second_tens
print(add_tens)
print(add_tens.size())

tensor([[13, 12, 14, 13],
        [18, 21, 21, 24]])
torch.Size([2, 4])


In [ ]:
#Subtraction:
sub_tens = first_tens - second_tens
print(sub_tens)
print(sub_tens.size())

tensor([[11,  8,  8,  5],
        [ 8,  9,  7,  8]])
torch.Size([2, 4])


#Creating tensors: GPU example

In [ ]:
if torch.cuda.is_available(): device = "cuda"
else: device = "cpu"
print(device)

cuda


In [ ]:
tens_a = torch.tensor([[12, 10, 11, 9], [13, 15, 14, 16]], device = device)
tens_b = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]],device = device)
multi_tens = tens_a * tens_b
print(multi_tens)

tensor([[ 12,  20,  33,  36],
        [ 65,  90,  98, 128]], device='cuda:0')


#Different ways to create tensors

In [ ]:
import torch
import numpy as np

#initialize a tensor from a python list

In [ ]:
tensor_from_list = torch.tensor([1, 2, 3, 4, 5])
print("tensor_from_list :", tensor_from_list)

tensor_from_list : tensor([1, 2, 3, 4, 5])


#initialize a tensor from a tuple

In [ ]:
tensor_from_tuple = torch.tensor((6, 7, 8, 9, 10))
print("tensor_from_tuple :", tensor_from_tuple)

tensor_from_tuple : tensor([ 6,  7,  8,  9, 10])


#initialize a tensor from a ndarray

In [ ]:
tensor_from_array= torch.tensor(np.array([11, 12, 13, 14, 15]))
print("Tensor from an array :", tensor_from_array)

Tensor from an array : tensor([11, 12, 13, 14, 15])


Other functions to create tensors
1. torch.empty()
2. torch.ones()
3. torch.zeros()

In [ ]:
tens_emp =torch.empty(3, 4)
tensor_zeros = torch.zeros(3, 4)
tensor_ones = torch.ones(2, 4)
print("tens_emp", tens_emp)
print("tensor_zeros", tensor_zeros)
print("tensor_ones ", tensor_ones )

tens_emp tensor([[6.8650e+01, 0.0000e+00, 6.8645e+01, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45, 2.1019e-44],
        [2.8026e-45, 4.4842e-44, 3.3631e-44, 0.0000e+00]])
tensor_zeros tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor_ones  tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
#Tensors initialized by size with random values
tensor_rand_un = torch.rand(4, 5)
print("tensor_rand_un", tensor_rand_un) #From uniform distribution

tensor_rand_un tensor([[0.1581, 0.3567, 0.5624, 0.0101, 0.7919],
        [0.4925, 0.2366, 0.5726, 0.8052, 0.0908],
        [0.0272, 0.3684, 0.6944, 0.2217, 0.8934],
        [0.4254, 0.7508, 0.9783, 0.3352, 0.6428]])


In [ ]:
#Tensor filled with random numbers from a normal distribution

#Tensor attributes

In [ ]:
first_tensor = torch.tensor([1, 2, 3, 4, 5, 6])
first_tensor.device

device(type='cpu')

In [ ]:
#datatype
first_tensor.dtype

torch.int64

In [ ]:
#shape of the tensor
first_tensor.shape

torch.Size([6])

In [ ]:
#dimension of the tensor
first_tensor.ndim

1

In [ ]:
second_tensor =torch.tensor([[1, 2, 3], [2, 3, 4]])

In [ ]:
second_tensor.dtype

torch.int64

In [ ]:
second_tensor.ndim

2

In [ ]:
second_tensor.shape

torch.Size([2, 3])

#Tensor datatypes

In [ ]:
import torch

In [ ]:
#integer data type tensor
int_tensor = torch.tensor([1, 2, 3, 4, 5], dtype =torch.int8)
int_tensor.dtype

torch.int8

In [ ]:
#float data type tensor
float_tensor = torch.tensor([1, 2, 3, 4, 5], dtype= torch.float32)
float_tensor.dtype

torch.float32

In [ ]:
#short data type tensor
short_tensor = torch.tensor([1, 2, 3, 4, 5], dtype =torch.int16)
short_tensor.dtype

torch.int16

In [ ]:
#Casting a tensor to a new data type (1st way)
int_tensor = int_tensor.float()
int_tensor.dtype

torch.float32

In [ ]:
#Casting tensor to a new data type (2nd way)
last_tensor = short_tensor.to(dtype=torch.int8)
last_tensor.dtype

torch.int8

#Creating tensors from random samples

torch.rand() selects random values from a uniform distribution on the interval [0-1]

In [ ]:
torch.rand(3,3)

tensor([[0.4726, 0.8618, 0.1704],
        [0.7747, 0.8275, 0.8662],
        [0.9808, 0.9573, 0.5825]])

In [ ]:
#To achieve the same result
torch.manual_seed(111)
torch.rand(3, 3)

tensor([[0.7156, 0.9140, 0.2819],
        [0.2581, 0.6311, 0.6001],
        [0.9312, 0.2153, 0.6033]])

#Creating a tensor like other tensors

In [ ]:
#To create a tensor of shape (2, 5) filled with ones
starting_tensor = torch.zeros(2, 5)
starting_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
#To create a tensor with the same size filled with random numbers
torch.manual_seed(111)
rand_tensor = torch.rand_like(starting_tensor)
rand_tensor

tensor([[0.7156, 0.9140, 0.2819, 0.2581, 0.6311],
        [0.6001, 0.9312, 0.2153, 0.6033, 0.7328]])

In [ ]:
#To create a tensor with the same shape filled with ones
torch.ones_like(rand_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
torch.full_like(starting_tensor, 7)

tensor([[7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]])

#Tensor Operations

###indexing 1-dim tensor example

In [ ]:
one_dim_tensor = torch.tensor([1, 2, 3, 4, 5])
print(one_dim_tensor[2])


tensor(3)


###slicing 1-dim tensor example

In [ ]:
one_dim_tensor[1:4]

tensor([2, 3, 4])

##indexing 2D tensor example

In [ ]:
two_dim_tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [5, 6, 7]])
two_dim_tensor[1][2]

tensor(6)

#Slicing 2-Dim tensor example

In [ ]:
print("First three elements of the 1st row: ", two_dim_tensor[0, 0:3])

First three elements of the 1st row:  tensor([1, 2, 3])


###Use indexing to extract the data that meets some criteria

In [ ]:
two_dim_tensor[two_dim_tensor<11]

tensor([1, 2, 3, 4, 5, 6, 5, 6, 7])

##Combining Tensor

In [ ]:
torch.stack((two_dim_tensor, two_dim_tensor))

tensor([[[1, 2, 3],
         [4, 5, 6],
         [5, 6, 7]],

        [[1, 2, 3],
         [4, 5, 6],
         [5, 6, 7]]])

###Splitting tensors

In [ ]:
first_tensor, second_tensor, third_tensor = torch.unbind(two_dim_tensor)
print(first_tensor, second_tensor, third_tensor)

tensor([1, 2, 3]) tensor([4, 5, 6]) tensor([5, 6, 7])


##Splitting 2-dim tensor

In [ ]:
torch.unbind(two_dim_tensor, dim=1)

(tensor([1, 4, 5]), tensor([2, 5, 6]), tensor([3, 6, 7]))

#Mathematical Functions



*   Pointwise operations
*   Reduction functions
*   Comparison functions
*   Linear algebra operations
*   Spectral and other math computations

#Pointwise operations:
Performs an operation on each point in the tensor individually and return a new tensor

Some commonly used pointwise operations are:

1. Basic math functions:
*   add()
*   mul()
*   div()
*   neg()
*   true_divide()

2. Functions for truncation:
*   ceil()
*   clamp()
*   floor()

3. Logical Functions


4. Trignometric functions etc...

In [ ]:
a = torch.tensor([10, 2, 8, 6, 7])
b = torch.tensor([3,4, 5, 6, 7])
print("Adding tensors a and b", a.add(b))
print("Subtracting tensors a and b", a.sub(b))
print("Multiplying tensors a and b", a.mul(b))
print("Dividing tensors a and b", a.div(b))

Adding tensors a and b tensor([13,  6, 13, 12, 14])
Subtracting tensors a and b tensor([ 7, -2,  3,  0,  0])
Multiplying tensors a and b tensor([30,  8, 40, 36, 49])
Dividing tensors a and b tensor([3.3333, 0.5000, 1.6000, 1.0000, 1.0000])


#Reduction Operations:
Reduce numbers down to a single number or a smaller set of numbers

--> Results in reducing the dimensionality or rank of a tensor

--> Include statistical operations such as mean, median or mode


In [ ]:
c = torch.tensor(([20., 24., 26., 25., 27.], [11., 12., 14., 17., 18.]))
print(f'Mean of the tensor c is {torch.mean(c)}')
print(f'Median of the tensor c is {torch.median(c)}')
print(f'Mode of the tensor c is {torch.mode(c)}')
print(f'Standard Deviation of the tensor c is {torch.std(c)}')

Mean of the tensor c is 19.399999618530273
Median of the tensor c is 18.0
Mode of the tensor c is torch.return_types.mode(
values=tensor([20., 11.]),
indices=tensor([0, 0]))
Standard Deviation of the tensor c is 5.9292120933532715


#Comparison Functions:


*   Compare all the values within a tensor or compare values of two different tensors.
*   Functions to find the minimum or maximum value, sort tensor values, test tensor status or condition and similar.



#Linear algebra functions:
* Enable matrix operations and are essential for deep learning computations
* Functions for matrix computations and tensor computations
* PyTorch has a module called torch.linalg that contains a set of built-in-linear algebra functions that are based on BLAS and LAPACK standardized libraries

###To compute the dot product (scalar)of two 1d tensors

In [ ]:
first_tensor= torch.tensor([1, 2, 3])
second_tensor = torch.tensor([4, 5, 6])

dot_product = torch.matmul(first_tensor, second_tensor)
dot_product

tensor(32)

###Compute the matrix-matrix product (2D tensor) of two 2d tensors

In [ ]:
first_2d_tensor = torch.tensor([[1, 2, 3], [-1, -2, -3]])
second_2d_tensor = torch.tensor([[1, 2], [-1, -2], [4, 5]])

result_2d_tensor = torch.matmul(first_2d_tensor, second_2d_tensor)
print(result_2d_tensor)

tensor([[ 11,  13],
        [-11, -13]])


###Compute the matrix product of 5 2d tensors

In [ ]:
first_ten = torch.randn(2, 3)
second_ten = torch.randn(3, 4)
third_ten =torch.randn(4, 5)
fourth_ten = torch.randn(5, 6)
fifth_ten = torch.randn(6, 7)

torch.linalg.multi_dot((first_ten, second_ten, third_ten, fourth_ten, fifth_ten))


tensor([[ 26.6664,   3.0291,   1.1834, -25.0146,  19.4369,  -3.2872,  -5.6789],
        [ -0.9047,  -4.4214,  -4.8463,   1.8508,  -4.2555,  -2.5432,  -6.1314]])

#Computing eigenvalues and eigenvectors

In [ ]:
A = torch.randn(3, 3)
print("Matrix: ", A)

eigenvalues, eigenvectors = torch.linalg.eig(A)
print("Eigen Values:", eigenvalues)
print("Eigen Vectors: ", eigenvectors)

Matrix:  tensor([[-0.7824, -1.3004,  1.8173],
        [-0.1650,  0.4930, -0.2092],
        [ 0.5015, -0.1266, -0.8037]])
Eigen Values: tensor([-1.7609+0.j, -0.1571+0.j,  0.8250+0.j])
Eigen Vectors:  tensor([[ 0.8868+0.j,  0.7691+0.j, -0.7759+0.j],
        [ 0.0221+0.j,  0.3642+0.j,  0.5639+0.j],
        [-0.4617+0.j,  0.5252+0.j, -0.2828+0.j]])


#Spectral Operations
--> Useful for data transformations and analysis.

#Automatic differentiation (Autograd):

